-- 赛季统计数据表
CREATE TABLE IF NOT EXISTS season_stats (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    player_id VARCHAR(50) NOT NULL COMMENT '球员ID',
    season_year VARCHAR(10) NOT NULL COMMENT '赛季年份',
    team_id VARCHAR(50) COMMENT '所属球队ID',
    gp INT COMMENT '出场次数',
    gs INT COMMENT '首发次数',
    min DECIMAL(6,2) COMMENT '出场时间',
    fgm INT COMMENT '投篮命中数',
    fga INT COMMENT '投篮尝试数',
    fg_pct DECIMAL(5,3) COMMENT '投篮命中率',
    fg3m INT COMMENT '三分命中数',
    fg3a INT COMMENT '三分尝试数',
    fg3_pct DECIMAL(5,3) COMMENT '三分命中率',
    ftm INT COMMENT '罚球命中数',
    fta INT COMMENT '罚球尝试数',
    ft_pct DECIMAL(5,3) COMMENT '罚球命中率',
    oreb INT COMMENT '进攻篮板',
    dreb INT COMMENT '防守篮板',
    reb INT COMMENT '总篮板',
    ast INT COMMENT '助攻',
    stl INT COMMENT '抢断',
    blk INT COMMENT '盖帽',
    tov INT COMMENT '失误',
    pf INT COMMENT '犯规',
    pts INT COMMENT '得分',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_player_season (player_id, season_year),
    INDEX idx_season_year (season_year),
    INDEX idx_team_id (team_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='球员赛季统计表';

-- 比赛表
CREATE TABLE IF NOT EXISTS games (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    game_id VARCHAR(50) NOT NULL COMMENT '比赛ID',
    game_date DATE NOT NULL COMMENT '比赛日期',
    home_team_id VARCHAR(50) NOT NULL COMMENT '主场球队ID',
    away_team_id VARCHAR(50) NOT NULL COMMENT '客场球队ID',
    home_team_score INT NOT NULL COMMENT '主场球队得分',
    away_team_score INT NOT NULL COMMENT '客场球队得分',
    season_year VARCHAR(10) NOT NULL COMMENT '赛季年份',
    game_type VARCHAR(20) COMMENT '比赛类型',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_game_id (game_id),
    INDEX idx_game_date (game_date),
    INDEX idx_season_year (season_year),
    INDEX idx_home_team (home_team_id),
    INDEX idx_away_team (away_team_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='比赛信息表';

-- 比赛详情表
CREATE TABLE IF NOT EXISTS game_details (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    game_id VARCHAR(50) NOT NULL COMMENT '比赛ID',
    player_id VARCHAR(50) NOT NULL COMMENT '球员ID',
    team_id VARCHAR(50) NOT NULL COMMENT '球队ID',
    is_home BOOLEAN NOT NULL COMMENT '是否主场',
    min DECIMAL(6,2) COMMENT '出场时间',
    fgm INT COMMENT '投篮命中数',
    fga INT COMMENT '投篮尝试数',
    fg_pct DECIMAL(5,3) COMMENT '投篮命中率',
    fg3m INT COMMENT '三分命中数',
    fg3a INT COMMENT '三分尝试数',
    fg3_pct DECIMAL(5,3) COMMENT '三分命中率',
    ftm INT COMMENT '罚球命中数',
    fta INT COMMENT '罚球尝试数',
    ft_pct DECIMAL(5,3) COMMENT '罚球命中率',
    oreb INT COMMENT '进攻篮板',
    dreb INT COMMENT '防守篮板',
    reb INT COMMENT '总篮板',
    ast INT COMMENT '助攻',
    stl INT COMMENT '抢断',
    blk INT COMMENT '盖帽',
    tov INT COMMENT '失误',
    pf INT COMMENT '犯规',
    pts INT COMMENT '得分',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_game_player (game_id, player_id),
    INDEX idx_game_id (game_id),
    INDEX idx_player_id (player_id),
    INDEX idx_team_id (team_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='比赛详细数据表';
